# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('was_tie', models.BooleanField(default=False)),
                ('was_overtime', models.BooleanField(default=False)),
                ('team1_win', models.BooleanField(default=False)),
                ('team1_goals', models.IntegerField(default=0)),
                ('team2_win', models.BooleanField(default=False)),
                ('team2_goals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HockeyLeague.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeaguePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='hockeyleague_leagueplugin', serialize=False, to='cms.CMSPlugin')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HockeyLeague.League')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('team_logo', models.ImageField(upload_to='team-logos/')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('overtime_losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('PTS', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HockeyLeague.League')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HockeyLeague.Team'),
        ),
        migrations.AddField(
            model_name='games',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HockeyLeague.League'),
        ),
        migrations.AddField(
            model_name='games',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='HockeyLeague.Team'),
        ),
        migrations.AddField(
            model_name='games',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='HockeyLeague.Team'),
        ),
    ]
