# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HockeyLeague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='HockeyLeague.Team'),
        ),
        migrations.AlterField(
            model_name='games',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='HockeyLeague.Team'),
        ),
    ]
