# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HockeyLeague', '0002_auto_20190502_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
