# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HockeyLeague', '0003_auto_20190502_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='HockeyLeague.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
