# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HockeyLeague', '0004_auto_20190509_0837'),
        ('HockeyLeague', '0002_auto_20190509_0844'),
    ]

    operations = [
    ]
