# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HockeyLeague', '0005_merge_20190509_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
