# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='schedules_schedule', serialize=False, to='cms.CMSPlugin')),
                ('schedule_name', models.CharField(blank=True, max_length=200)),
                ('schedule_start_date', models.DateTimeField(verbose_name='Start Date')),
                ('schedule_end_date', models.DateTimeField(verbose_name='End Date')),
                ('schedule_file_name', models.FileField(upload_to='', verbose_name='File Path')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
